### PR TITLE
Fix import behavior

### LINKED ISSUE #70: Import no longer clears and centers canvas
## Describe the bug
Import no longer fires `import.start` and `import.end` after #65.

## To Reproduce
1. Add elements to the canvas by drawing or importing
2. Import file
3. Imported elements are added to the existing elements
4. View transform remains unchanged

## Expected behavior
1. Canvas is cleared before adding imported elements
2. View focuses on imported elements

## Additional context
The test for this behavior should be more thorough.

### PR DESCRIPTION
**Pull request by 0x4d**
Closes #70 

## Describe your changes
- Added new argument `middleware` when firing import events
- Improved test to detect if this fails in the future

### CODE REVIEW

**Comment by tim-kilian** [comment]
Could you add some tests for your changes?

**Comment by 0x4d** [comment]
> Could you add some tests for your changes?

I do test all the things I changed. Look at the code :sweat_smile:

I added a test to see wether the canvas actually moved to the branch to make codecov happy :grin:

File: src/features/import/behaviors/MetaImportBehavior.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ export class MetaImportBehavior extends Behavior {
         const plugin = this.metaPluginManager.getPlugin(context.model);
         const parser = plugin.getParser(context.format);
         const data = parser.parse(context.data);
-        this.eventBus.fire('import', { data });
+        this.eventBus.fire('import', { data }, true);
```
Comment (tim-kilian) [inline src/features/import/behaviors/MetaImportBehavior.js:16]: Nice to see, that you're using this parameter.

**Review by tim-kilian — APPROVED** [review]
