### PR TITLE
Apply viewbox to direct editing

### LINKED ISSUE #95: Label direct editing ignores viewport transform
## Describe the bug
1. Direct label editing ignores viewport transform
2. Shape placed after direct editing has wrong coordinates

## To Reproduce
1. Translate the canvas
2. Start creating a label
3. The direct editing box uses the viewport coordinates as screen coordinates

## Expected behavior
Screen coordinates should be translated

### PR DESCRIPTION
**Pull request by 0x4d**
Closes #95 

## Describe your changes
Apply the current viewbox transformation matrix to the direct editing bounds

### CODE REVIEW

File: src/features/edit/commands/EditLabelCommand.js [hunk 1]
```diff
@@ -3,27 +3,25 @@ import { Command } from '../../../core/command/Command';
...
-        context.label.width = context.bounds.width;
-        context.label.height = context.bounds.height;
+        context.label.width = context.bounds.width / viewbox.scale;
+        context.label.height = context.bounds.height / viewbox.scale;
     }
 
     postExecute (context) {
         const element = context.label;
-        const gfx = this.elementRegistry.getGraphics(element.id);
+        const gfx = this.canvas.getElementRegistry().getGraphics(element.id);
```
Comment (tim-kilian) [inline src/features/edit/commands/EditLabelCommand.js:21]: Nice use of getter, I've moved this update process to the canvas.

**Review by tim-kilian — APPROVED** [review]
